# Project configuration
version: 2 


build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pipx install uv
      - UV_PROJECT_ENVIRONMENT="$READTHEDOCS_VIRTUALENV_PATH" uv sync --dev --link-mode=copy

sphinx:
  configuration: docs/source/conf.py
