[options]
log_level = "INFO"
max_threads = 5 # Limit parallel actions to 5 threads

[[hosts]]
name = "host1"
ip = "host1.example.com"

[[hosts]]
name = "host2"
ip = "host2.example.com"
port = 2222
description = "Example Host"

[[hosts]]
name = "host3"
ip = "host3.example.com"
description = "Another Example Host"