name: Build Docker Image

on:
  workflow_run:
    workflows: ["Exosphere Test Suite"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag exosphere:$(date +%s)
